apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  DJANGO_SETTINGS_MODULE: "{{ .Values.env.DJANGO_SETTINGS_MODULE }}"
  DEBUG: "{{ .Values.env.DEBUG }}"
  ALLOWED_HOSTS: {{ .Values.env.ALLOWED_HOSTS | quote }}
